// src/templates/welcomeEmail.js

/**
 * Generates a styled HTML + plaintext welcome email
 * for new BGI members.
 *
 * @param {Object} params
 * @param {string} params.name - Full name of member
 * @param {string} params.itsNumber - ITS number
 * @param {string} params.email - Member's email
 * @param {string} params.password - Assigned password
 * @param {string} params.loginUrl - Portal login URL
 * @returns {{ html: string, text: string }}
 */
export function welcomeEmailTemplate({ name, itsNumber, email, password, loginUrl }) {
  const displayName = name || "Member";
  const displayIts = itsNumber || "—";
  const displayEmail = email || "—";
  const displayPassword = password || "—";
  const loginLink = loginUrl || "http://localhost:3000/login";

  // HTML body (works with most mail clients, minimal inline CSS)
  const html = `
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Welcome to BGI</title>
    </head>
    <body style="margin:0; padding:0; font-family:Arial,Helvetica,sans-serif; background:#f3f6fb; color:#333;">
      <table width="100%" cellpadding="0" cellspacing="0" role="presentation" style="background:#f3f6fb; padding:20px 0;">
        <tr>
          <td align="center">
            <table width="600" cellpadding="0" cellspacing="0" role="presentation" style="background:#ffffff; border-radius:8px; overflow:hidden;">
              
              <!-- Header -->
              <tr>
                <td style="padding:20px; background:linear-gradient(90deg,#1976d2,#42a5f5); color:#ffffff; text-align:left;">
                  <h1 style="margin:0; font-size:20px; font-weight:bold;">Burhani Guards International</h1>
                  <p style="margin:4px 0 0; font-size:13px;">Welcome to BGI — Member Portal</p>
                </td>
              </tr>

              <!-- Body -->
              <tr>
                <td style="padding:24px;">
                  <p style="font-size:14px; margin:0 0 12px;">Dear <strong>${displayName}</strong>,</p>

                  <p style="font-size:14px; margin:0 0 16px;">
                    Your profile has been successfully created on the BGI portal.
                  </p>

                  <table cellpadding="6" cellspacing="0" style="border-collapse:collapse; margin:12px 0; font-size:14px;">
                    <tr>
                      <td style="font-weight:600; width:140px;">ITS Number</td>
                      <td>${displayIts}</td>
                    </tr>
                    <tr>
                      <td style="font-weight:600;">Email</td>
                      <td>${displayEmail}</td>
                    </tr>
                    <tr>
                      <td style="font-weight:600;">Password</td>
                      <td style="font-family:monospace; background:#f6f8fb; padding:6px 8px; border-radius:4px;">${displayPassword}</td>
                    </tr>
                  </table>

                  <p style="font-size:14px; margin:16px 0;">
                    You can login here: 
                    <a href="${loginLink}" target="_blank" style="color:#1976d2; text-decoration:none;">${loginLink}</a>
                  </p>

                  <p style="font-size:14px; margin:16px 0;">
                    Please change your password after first login.
                  </p>

                  <hr style="border:none; border-top:1px solid #eee; margin:18px 0;" />

                  <p style="font-size:12px; color:#777; margin:0;">
                    Note: This is an autogenerated mail. Please do not reply.
                  </p>
                </td>
              </tr>

              <!-- Footer -->
              <tr>
                <td style="background:#fafafa; padding:12px 24px; font-size:12px; color:#888; text-align:center;">
                  © ${new Date().getFullYear()} Burhani Guards International. All rights reserved.
                </td>
              </tr>

            </table>
          </td>
        </tr>
      </table>
    </body>
  </html>
  `;

  // Plain-text fallback
  const text = `Dear ${displayName},

Your profile has been created on the BGI portal.

ITS Number: ${displayIts}
Email: ${displayEmail}
Password: ${displayPassword}

Login: ${loginLink}

Please change your password after first login.

Note: This is an autogenerated mail. Please do not reply.
`;

  return { html, text };
}
