import mongoose from "mongoose";

const paymentSchema = new mongoose.Schema(
  {
    memberId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    memberName: { type: String, required: true },
    itsNumber: { type: String, required: true },
    zone: { type: String, required: true },
    
    // Payment details
    amount: { type: Number, required: true },
    paymentType: {
      type: String,
      enum: ["Joining Fee", "Annual Subscription", "Event Fee", "Fine", "Other"],
      default: "Annual Subscription",
    },
    paymentMethod: {
      type: String,
      enum: ["Cash", "UPI", "Bank Transfer", "Cheque", "Online"],
      default: "Cash",
    },
    
    // Status tracking
    status: {
      type: String,
      enum: ["Paid", "Pending", "Overdue", "Partial"],
      default: "Pending",
    },
    
    // Financial year for subscriptions
    subscriptionYear: { type: String }, // e.g., "2024-2025" (for annual subscriptions)
    dueDate: { type: Date, required: true },
    paidDate: { type: Date },
    
    // Additional info
    transactionId: { type: String },
    remarks: { type: String },
    receiptNumber: { type: String },
    
    // Payment proof
    paymentProof: { type: String }, // URL to uploaded proof
    
    // Who recorded this payment
    recordedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    },
    
    // Auto-generated flag for annual subscriptions
    autoGenerated: { type: Boolean, default: false },
  },
  { timestamps: true }
);

// Index for faster queries
paymentSchema.index({ memberId: 1, subscriptionYear: 1 });
paymentSchema.index({ status: 1 });
paymentSchema.index({ itsNumber: 1 });
paymentSchema.index({ paymentType: 1 });
paymentSchema.index({ dueDate: 1 });

// Automatically set receipt number on creation if paid
paymentSchema.pre("save", function (next) {
  if (this.isNew && this.status === "Paid" && !this.receiptNumber) {
    this.receiptNumber = `RCP${Date.now()}${Math.floor(Math.random() * 1000)}`;
  }
  next();
});

export default mongoose.models.Payment || mongoose.model("Payment", paymentSchema);